apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nexus-repository-manager
      app.kubernetes.io/component: nexus-repository-manager
      app.kubernetes.io/instance: nexus-repository-manager
    name: nexus-repository-manager
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.connect.redhat.com/sonatype/nexus-repository-manager:3.40.1-ubi-1
      from:
        kind: DockerImage
        name: registry.connect.redhat.com/sonatype/nexus-repository-manager:3.40.1-ubi-1
      generation: null
      importPolicy: {}
      name: 3.40.1-ubi-1
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"nexus-repository-manager:3.40.1-ubi-1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nexus-repository-manager\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nexus-repository-manager
      app.kubernetes.io/component: nexus-repository-manager
      app.kubernetes.io/instance: nexus-repository-manager
    name: nexus-repository-manager
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: nexus-repository-manager
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: nexus-repository-manager
      spec:
        containers:
        - image: ' '
          name: nexus-repository-manager
          ports:
          - containerPort: 8081
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /nexus-data
            name: nexus-repository-manager-volume-1
        volumes:
        - emptyDir: {}
          name: nexus-repository-manager-volume-1
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nexus-repository-manager
      app.kubernetes.io/component: nexus-repository-manager
      app.kubernetes.io/instance: nexus-repository-manager
    name: nexus-repository-manager
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      deployment: nexus-repository-manager
  status:
    loadBalancer: {}
kind: List
metadata: {}
